server:
  port: 9090

spring:
  application:
    name: process-service
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flowable?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 169167866Spl.

flowable:
  idm:
    enabled: false # 检测身份信息
  database-schema-update: true # 没有数据库表的时候生成数据库表

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#  configuration:
#    #控制台打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

